DROP TABLE IF EXISTS `student`;
CREATE TABLE IF NOT EXISTS `student`
(
   `studentid` integer generated by default as identity,
   age integer not null check
   (
      age<= 120
      AND
         age>= 1
   ),
   contact_number varchar (255),
   first_name varchar (255) not null,
   last_name varchar (255),
   parent_name varchar (255),
   primary key (studentid)
);